services:
  python:
    build:
      context: .
      dockerfile: Dockerfile
    init: true
    stdin_open: true
    tty: true
    working_dir: /app
    volumes:
      - ..:/app

      - sample_project_venv:/app/python-projects/sample_project/.venv
      - python_uv_cache:/root/.cache/uv

volumes:
  sample_project_venv:
  python_uv_cache:
